import json
import os
from pathlib import Path

# Paths
ROOT_DIR = Path(__file__).parent.parent.parent
SCHEMAS_DIR = ROOT_DIR / "data" / "schemas"
GENERATED_DIR = ROOT_DIR / "src" / "iso8583_manager" / "core" / "models" / "generated"

JSON_FILE = SCHEMAS_DIR / "iso8583_fields.json"
MODELS_FILE = GENERATED_DIR / "iso_models.py"

def generate_models():
    """
    Reads iso8583_fields.json and generates Pydantic model in iso_models.py
    """
    if not JSON_FILE.exists():
        print(f"Schema file not found: {JSON_FILE}")
        return

    with open(JSON_FILE, "r", encoding="utf-8") as f:
        fields = json.load(f)

    # Ensure generated directory exists
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    (GENERATED_DIR / "__init__.py").touch(exist_ok=True)

    header = '''"""
This file is auto-generated by scripts/code_generator/generate_models.py.
DO NOT EDIT MANUALLY!
"""

from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, ClassVar
from iso8583_manager.core.interfaces.iso_ports import IIso8583Model

class Iso8583MessageModel(BaseModel):
    """
    Auto-generated Pydantic model for ISO 8583 Data Elements.
    """
'''

    with open(MODELS_FILE, "w", encoding="utf-8") as out:
        out.write(header)
        
        # Meta mapping mapping property names to field IDs
        field_mapping_code = "\n    # Property name to ISO Field ID mapping\n    field_mapping: ClassVar[Dict[str, str]] = {\n"
        
        for field_id, metadata in fields.items():
            prop_name = metadata["name"]
            desc = metadata.get("description", "")
            max_len = metadata.get("max_len")
            
            # Pydantic Field arguments
            field_args = [f'description="{desc}"']
            if max_len:
                field_args.append(f"max_length={max_len}")
                
            field_def = f"    {prop_name}: Optional[str] = Field(default=None, {', '.join(field_args)})\n"
            out.write(field_def)
            
            field_mapping_code += f'        "{prop_name}": "{field_id}",\n'
            
        field_mapping_code += "    }\n\n"
        out.write(field_mapping_code)
        
        # Implement IIso8583Model interface
        out.write('''    def to_iso_dict(self) -> Dict[str, Any]:
        """Convert populated fields to dict of string IDs for pyiso8583."""
        result = {}
        dumped = self.model_dump(exclude_unset=True, exclude_none=True)
        for key, value in dumped.items():
            if key in self.field_mapping:
                iso_id = self.field_mapping[key]
                result[iso_id] = str(value)
        return result

    @classmethod
    def from_iso_dict(cls, data: Dict[str, Any]) -> "IIso8583Model":
        """Create model instance from pyiso8583 decoded dict."""
        # Reverse mapping: iso_id to prop_name
        reverse_map = {v: k for k, v in cls.field_mapping.items()}
        kwargs = {}
        for k, v in data.items():
            if k in reverse_map:
                kwargs[reverse_map[k]] = v
        return cls(**kwargs)
''')

    print(f"Models successfully generated at {MODELS_FILE}")

if __name__ == "__main__":
    generate_models()
